### ISSUE TITLE
[docs] 기능정의서 작성

### ISSUE THREAD

**Issue by joyful-young** [Book-Eating-Bunny/BEB-BE#1]
##  ✍🏻 이슈내용
- 프로젝트 기능정의서 작성
<br>

##  📑 이슈 상세 내용
- 필요 기능을 3 depth로 나누어 노션에 상세히 작성
  - [기능정의서 노션 링크](https://www.notion.so/IA-13b91c17c59081e4b41ec6dc11e4e892)
- version 1 `회원가입-로그인-프로필 관리-읽은 책 추가-서평 작성-문구 저장-기록 조회-로그아웃` 기능 구체화
- version 2의 커뮤니티 기능까지 고려하여 작성
<br>

## 진행 중 기획 변경 사항
- 인상 깊은 문구 저장 기능은 삭제함
- 읽고 싶은 책 추가 기능(찜하기)을 추가함
<br>

##  ✅ 체크리스트
- [x] version1(유저 관리, 개인 독서 기록)에 필요한 기능 작성
- [x] 기획 내용의 일치 여부 확인을 위한 타팀원의 검토
- [x] 사용자의 입력을 받을 때 제한 형식 상세하게 작성
- [x] 조회 페이지에서 어떤 항목들을 보여주는지 구체적으로 작성
<br>

##  🚎 레퍼런스 
- [기능정의서 예시](https://yoonwookim.notion.site/58714ea3bcd247399f82e125b74d4177)

**Comment by MinWoongL** [comment]
@joyful-young 기능정의서 notion 접근권한 요청드립니다 :)
