### ISSUE TITLE
[feat] 회원가입 기능 구현

### ISSUE THREAD

**Issue by joyful-young** [Book-Eating-Bunny/BEB-BE#12]
##  ✍🏻 이슈내용
- 회원가입 기능 구현
<br>

##  📑 이슈 상세 내용
- #10, #11 에서 회원 기능을 위한 객체 설계하고 
인증 과정 정한 것 바탕으로 회원가입 기능 구현
<br>

##  ✅ 체크리스트
- [x] DB에 회원 테이블 생성
- [x] 회원 가입 시 필요한 정보 전달하는 DTO 객체 구현
- [x] 입력한 정보 유효성 검사 (validation 라이브러리 이용)
- [x] 정보를 받아 계정을 생성해서 DB에 저장, 토큰 발급
<br>

**Comment by MinWoongL** [comment]
@joyful-young 완성되면 회원가입 하겠습니다~

**Comment by BTDnoBacon** [comment]
자바왕 박재영
