### ISSUE TITLE
[feat] 현재 사용자가 읽은 책 목록 조회 기능 구현

### ISSUE THREAD

**Issue by joyful-young** [Book-Eating-Bunny/BEB-BE#37]
##  ✍🏻 이슈내용
- 현재 인증된 사용자가 읽은 책 목록을 조회하는 기능 구현
<br>

##  📑 이슈 상세 내용
- 토큰으로부터 현재 인증된 사용자 정보 가져와 그 사용자가 기록한 읽은 책의 목록을 조회
- 페이지네이션 적용
- 책의 정보(도서ID(PK), 표지, 제목, 저자, 평균 평점) 포함
<br>

##  ✅ 체크리스트
- [x] 현재 사용자가 읽은 책 조회
- [x] 조회할 페이지(page), 페이지 내 데이터 수(size)에 따라 결과 달라져야 함
- [x] 읽은 책이 없을 경우 data를 빈 배열로 반환
- [x] meta에 페이지네이션 정보(현재 페이지, 전체 페이지 수, 전체 데이터 수) 함께 반환
<br>

**Comment by BTDnoBacon** [comment]
페이지네이션까지 캬~
